development:
  adapter: postgresql
  encoding: unicode
  database: pro_football_api_development
  pool: 5
  username: pro_football_api
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: pro_football_api_test
  pool: 5
  username: pro_football_api
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: pro_football_api_production
  pool: 5
  username: pro_football_api
  password:
